# -*- coding: utf-8 -*-
"""day21-bivariate-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S8x5bcwKnuBDMAsEgyf2ZZo5J_SYNwNi
"""

import pandas as pd
import seaborn as sns

tips = sns.load_dataset('tips')

tips.head()

titanic = pd.read_csv('/content/train.csv')

flights = sns.load_dataset('flights')

flights.head()

iris = sns.load_dataset('iris')

iris

"""# **1. Scatterplot (Numerical - Numerical)**"""

sns.scatterplot(x=tips['total_bill'], y=tips['tip'], hue=tips['sex'], style=tips['smoker'], size=tips['size'])

"""# **2. Bar Plot (Numerical - Categorical)**"""

titanic.head()

sns.barplot(x=titanic['Pclass'],y=titanic['Age'],hue=titanic['Sex'])

"""# **3. Box Plot (Numerical - Categorical)**"""

sns.boxplot(x=titanic['Sex'],y=titanic['Age'],hue=titanic['Survived'])

"""# **4. Distplot (Numerical - Categorical)**"""

sns.distplot(titanic[titanic['Survived']==0]['Age'],hist=False)
sns.distplot(titanic[titanic['Survived']==1]['Age'],hist=False)

"""# **5. HeatMap (Categorical - Categorical)**"""

titanic.head(3)

sns.heatmap(pd.crosstab(titanic['Pclass'],titanic['Survived']))

(titanic.groupby('Embarked').mean(numeric_only=True)['Survived']*100)

"""# **6. ClusterMap (Categorical - Categorical)**"""

sns.clustermap(pd.crosstab(titanic['Parch'],titanic['Survived']))

"""# **7. Pairplot**"""

iris.head()

sns.pairplot(iris,hue='species')

"""# **8. Lineplot (Numerical - Numerical)**"""

flights.head()

new = flights.groupby('year').agg({'passengers': 'sum'}).reset_index()

sns.lineplot(x='year', y='passengers', data=new)

flights

sns.clustermap(flights.pivot_table(values='passengers',index='month',columns='year'))