# -*- coding: utf-8 -*-
"""day-20-univariate-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_QyBBdFa5mqnokSo6Tb6nhkW_maklW_C
"""

import pandas as pd
import seaborn as sns

df = pd.read_csv('/content/train.csv')

df.head()

"""#**1. Categorical Data**

**a. Countplot**
"""

sns.countplot(df['Embarked'])
#df['Survived'].value_counts().plot(kind='bar')

"""**b. PieChart**"""

df['Sex'].value_counts().plot(kind='pie',autopct='%.2f')

"""# **2. Numerical Data**

**a. Histogram**
"""

import matplotlib.pyplot as plt
plt.hist(df['Age'],bins=10)

"""**b. Distplot**"""

sns.distplot(df['Age'])

"""**c. Boxplot**"""

sns.boxplot(df['Age'])

df['Age'].min()

df['Age'].max()

df['Age'].mean()

df['Age'].skew()