# -*- coding: utf-8 -*-
"""day26-ordinal-encoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cu1hJsoPmoJwTkNfcLt_GZ4T7dGf4sqq
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/customer.csv')

df.sample(5)

df = df.iloc[:,2:]

df.head()

from sklearn.preprocessing import OrdinalEncoder

from sklearn.model_selection import train_test_split
X = df.drop('purchased', axis=1)
y = df['purchased']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train

oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

X_train = oe.transform(X_train)

X_train

oe.categories_

X_train

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(y_train)

le.classes_

y_train = le.transform(y_train)
y_test = le.transform(y_test)

y_train