# -*- coding: utf-8 -*-
"""how-feature-importance-is-calculated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17n_N-iLQIGD_fg2wvWhwolYSH2k3onNc
"""

from sklearn.datasets import make_classification

from sklearn.tree import DecisionTreeClassifier

X,y = make_classification(n_samples=5, n_classes=2,
                               n_features=2, n_informative=2, n_redundant=0,
                               random_state=0)

clf = DecisionTreeClassifier()

clf.fit(X,y)

from sklearn.tree import plot_tree
plot_tree(clf)

clf.feature_importances_

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=2)
rf.fit(X,y)

rf.feature_importances_

print(rf.estimators_[0].feature_importances_)
print(rf.estimators_[1].feature_importances_)

print((1 + 0.555)/2)

X,y = make_classification(n_samples=15, n_classes=2,
                               n_features=2, n_informative=2, n_redundant=0,
                               random_state=0)

from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()

clf.fit(X,y)

from sklearn.tree import plot_tree
plot_tree(clf)

clf.feature_importances_