# -*- coding: utf-8 -*-
"""classification-metrics-multi-mnist1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t7ATZ0vtdDUNFGzgoZy35WSbbZwBhZDz
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/train.csv')
df.head()

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=2)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

from sklearn.metrics import precision_score,recall_score,f1_score

precision_score(y_test,y_pred1,average='weighted')

recall_score(y_test,y_pred1,average='weighted')

f1_score(y_test,y_pred1,average='weighted')

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))