# -*- coding: utf-8 -*-
"""day-19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o_mByN8spCTcLy4FJv4BN5_SmAKer_KU
"""

import pandas as pd

df = pd.read_csv('/content/train.csv')

"""1. How big is the data?"""

df.shape

"""2. How does the data look like?"""

df.sample(5)

"""3. What is the data type of cols?"""

df.info()

"""4. Are there any missing values?"""

df.isnull().sum()

"""5. How does the data look mathematically?"""

df.describe()

"""6. Are there duplicate values?"""

df.duplicated().sum()

"""7. How is the correlation between cols?"""

df.corr(numeric_only=True)['Survived']